const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');let W=420,H=700,score=0,life=3,objects=[],particles=[],texts=[],player={x:210,y:610,w:78,h:92,vx:0},keys={left:false,right:false};let raf=0,last=0,spawnClock=0,diffClock=0,gameState='home';window.gameState=gameState;
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0)}window.addEventListener('resize',resize);resize();
function startGame(){cancelAnimationFrame(raf);score=0;life=3;objects=[];particles=[];texts=[];player.x=W/2;spawnClock=0;diffClock=0;gameState='playing';window.gameState=gameState;document.getElementById('score').textContent=fmt(score);document.getElementById('life').textContent='❤️❤️❤️';updateHigh();startMusic();last=performance.now();raf=requestAnimationFrame(loop)}
function stopGame(){cancelAnimationFrame(raf);stopMusic();gameState='home';window.gameState=gameState}
function pauseGame(){if(gameState!=='playing')return;gameState='paused';window.gameState=gameState;stopMusic();modal('pauseModal',true)}function resumeGame(){if(gameState!=='paused')return;modal('pauseModal',false);gameState='playing';window.gameState=gameState;startMusic();last=performance.now();raf=requestAnimationFrame(loop)}
function spawn(){const r=Math.random();let type=r<.63?'tofu':r<.84?'chili':'bomb';objects.push({type,x:25+Math.random()*(W-50),y:-35,vy:150+Math.random()*90+(diffClock/1000)*3,size:type==='bomb'?30: type==='chili'?26:32,rot:Math.random()*6})}
function loop(t){if(gameState!=='playing')return;const dt=Math.min((t-last)/1000,.035);last=t;diffClock+=dt*1000;spawnClock-=dt*1000;const interval=Math.max(260,720-diffClock*.045);if(spawnClock<=0){spawn();if(diffClock>12000&&Math.random()<.25)spawn();spawnClock=interval}update(dt);draw();raf=requestAnimationFrame(loop)}
function update(dt){const speed=310;if(keys.left)player.x-=speed*dt;if(keys.right)player.x+=speed*dt;player.x=Math.max(48,Math.min(W-48,player.x));objects.forEach(o=>{o.y+=o.vy*dt;o.rot+=dt*2});for(let i=objects.length-1;i>=0;i--){const o=objects[i];if(Math.abs(o.x-player.x)<(o.size+player.w*.38)&&Math.abs(o.y-player.y)<(o.size+player.h*.38)){catchObj(o);objects.splice(i,1)}else if(o.y>H+50)objects.splice(i,1)}particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=350*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);texts.forEach(x=>{x.y-=30*dt;x.life-=dt});texts=texts.filter(x=>x.life>0)}
function catchObj(o){if(o.type==='bomb'){life--;sfx('bomb');shake=0.25;burst(o.x,o.y,'#fff',14);document.getElementById('life').textContent='❤️'.repeat(life)+'🖤'.repeat(3-life);if(navigator.vibrate)navigator.vibrate(120);if(life<=0)endGame()}else{const pts=o.type==='chili'?20:10;score+=pts;sfx(o.type);document.getElementById('score').textContent=fmt(score);texts.push({x:o.x,y:o.y,txt:'+'+pts,life:.65});burst(o.x,o.y,o.type==='chili'?'#ff3030':'#ffd34e',9)}}
let shake=0;function burst(x,y,c,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:-Math.random()*180-40,life:.5+Math.random()*.4,c})}
function endGame(){gameState='over';window.gameState=gameState;stopMusic();cancelAnimationFrame(raf);const old=Number(localStorage.getItem('tahuRushHigh')||0),isNew=score>old;if(isNew)localStorage.setItem('tahuRushHigh',score);document.getElementById('finalScore').textContent=fmt(score);document.getElementById('finalHigh').textContent=fmt(Math.max(score,old));document.getElementById('newHigh').classList.toggle('show',isNew);updateHigh();modal('gameOverModal',true);sfx('over')}
function draw(){ctx.save();if(shake>0){shake-=.016;ctx.translate((Math.random()-.5)*10,(Math.random()-.5)*10)}drawBg();objects.forEach(drawObject);drawPlayer();particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*1.5);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,3+p.life*3,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;texts.forEach(x=>{ctx.font='900 24px Arial';ctx.textAlign='center';ctx.fillStyle='#fff';ctx.strokeStyle='#8b3d14';ctx.lineWidth=5;ctx.strokeText(x.txt,x.x,x.y);ctx.fillText(x.txt,x.x,x.y)});ctx.restore()}
function drawBg(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#5bc8e8');g.addColorStop(.6,'#a5e3d4');g.addColorStop(1,'#e8a85c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffffff55';for(let i=0;i<18;i++){ctx.beginPath();ctx.arc((i*83)%W,100+(i*57)%450,2+(i%3),0,Math.PI*2);ctx.fill()}ctx.fillStyle='#9b5c2b';ctx.fillRect(0,H-125,W,125);ctx.fillStyle='#f3c35b';ctx.fillRect(0,H-128,W,8);ctx.fillStyle='#7c421e';ctx.fillRect(12,H-108,90,55);ctx.fillStyle='#fff0a0';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.fillText('TAHU GEJROT',57,H-84);ctx.fillText('PAKDE BURUNG',57,H-68);ctx.fillStyle='#743d20';ctx.fillRect(320,H-100,78,8);ctx.fillRect(330,H-92,8,52);ctx.fillRect(380,H-92,8,52)}
function drawObject(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rot);if(o.type==='tofu'){ctx.shadowColor='#0005';ctx.shadowBlur=8;ctx.fillStyle='#f4b84c';roundRect(-17,-17,34,34,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#ffe29a';ctx.fillRect(-10,-10,5,5);ctx.fillRect(4,-4,4,4);ctx.fillStyle='#d67c23';ctx.fillRect(-13,9,25,3)}else if(o.type==='chili'){ctx.fillStyle='#e92d31';ctx.beginPath();ctx.moveTo(-7,-12);ctx.quadraticCurveTo(13,-4,8,12);ctx.quadraticCurveTo(0,25,-11,12);ctx.quadraticCurveTo(-17,1,-7,-12);ctx.fill();ctx.fillStyle='#39a94a';ctx.beginPath();ctx.arc(-4,-13,6,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#252525';ctx.beginPath();ctx.arc(0,2,16,0,Math.PI*2);ctx.fill();ctx.fillStyle='#eee';ctx.beginPath();ctx.arc(-5,0,3,0,Math.PI*2);ctx.arc(5,0,3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ff8d26';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(5,-14);ctx.lineTo(12,-25);ctx.stroke();ctx.fillStyle='#ffb13b';ctx.beginPath();ctx.arc(13,-27,4,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);const moving=keys.left||keys.right;ctx.rotate(moving?(keys.left?-.05:.05):0);ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(-22,43,20,8,0,0,Math.PI*2);ctx.ellipse(22,43,20,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3975bb';ctx.fillRect(-28,4,56,42);ctx.fillStyle='#ff5b96';roundRect(-31,-5,62,55,18);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 6px Arial';ctx.textAlign='center';ctx.fillText('TAHU GEJROT',0,21);ctx.fillText('PAKDE BURUNG',0,29);ctx.fillStyle='#ffd1b4';ctx.beginPath();ctx.arc(0,-39,37,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e6aa56';ctx.beginPath();ctx.arc(0,-47,39,Math.PI,Math.PI*2);ctx.fill();ctx.fillRect(-38,-48,12,34);ctx.fillRect(26,-48,12,34);ctx.fillStyle='#4a2a22';ctx.beginPath();ctx.ellipse(-12,-40,5,8,0,0,Math.PI*2);ctx.ellipse(12,-40,5,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-13,-43,2,0,Math.PI*2);ctx.arc(11,-43,2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#bd5360';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-29,10,0,Math.PI);ctx.stroke();ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function bindHold(id,key){const b=document.getElementById(id);['pointerdown','touchstart'].forEach(e=>b.addEventListener(e,ev=>{ev.preventDefault();keys[key]=true},{passive:false}));['pointerup','pointercancel','pointerleave','touchend'].forEach(e=>b.addEventListener(e,ev=>{ev.preventDefault();keys[key]=false},{passive:false}))}bindHold('leftBtn','left');bindHold('rightBtn','right');window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')keys.left=true;if(e.key==='ArrowRight')keys.right=true});window.addEventListener('keyup',e=>{if(e.key==='ArrowLeft')keys.left=false;if(e.key==='ArrowRight')keys.right=false});let swipeX=null;canvas.addEventListener('pointerdown',e=>swipeX=e.clientX);canvas.addEventListener('pointermove',e=>{if(swipeX!==null){const dx=e.clientX-swipeX;if(Math.abs(dx)>8){player.x+=dx*.9;player.x=Math.max(48,Math.min(W-48,player.x));swipeX=e.clientX}}});canvas.addEventListener('pointerup',()=>swipeX=null);canvas.addEventListener('pointercancel',()=>swipeX=null);
